name: aws_common
description: Common types and utilities for AWS packages.
version: 0.1.0
homepage: https://github.com/awslabs/aws-sdk-dart
issue_tracker: https://github.com/awslabs/aws-sdk-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  json_annotation: ">=4.4.0 <4.5.0"
  async: ^2.8.2
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
