name: example
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  amplify_ui_angular:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
