name: amplify_appsync
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  amplify_common:
    path: ../amplify_common
  async: ^2.6.0
  aws_signature_v4:
    path: ../../aws_signature_v4
  collection: ^1.15.0
  equatable: ^2.0.0
  web_socket_channel: ^2.1.0
  uuid: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
