name: aws_s3
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aws_common:
    path: ../aws_common
  aws_signature_v4:
    path: ../aws_signature_v4
  file: ^6.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
