name: amplify_headless_interface
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
  json_schema_builder: 
    path: ../json_schema_builder
  path: ^1.8.0
  recase: ^4.0.0
  tar: ^0.5.0
  test: ^1.16.0
